// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EngineReloadRequest {
    /// Path to the data file to be loaded in a new engine.
    #[prost(string, required, tag = "2")]
    pub file_path: ::prost::alloc::string::String,
    /// Explicitly specifies the magic number to be used for data validation.
    /// Since acceptable magic number is embedded in Mozc server, this option is
    /// unnecessary for normal cases.  However, this is required for some unit
    /// tests as test data has a different magic number.
    #[prost(string, optional, tag = "4")]
    pub magic_number: ::core::option::Option<::prost::alloc::string::String>,
    /// Priority of the request (smaller is more prioritized).
    /// The decoder keeps all the requests, and uses the most prioritized one.
    /// For the same priority request, later one overrides existing one.
    /// Effective only with CommandType.SEND_ENGINE_RELOAD_REQUEST.
    #[prost(int32, optional, tag = "5")]
    pub priority: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EngineReloadResponse {
    #[prost(enumeration = "engine_reload_response::Status", required, tag = "1")]
    pub status: i32,
    /// The original request is copied in response for convenience (the reload
    /// command runs asynchronously but client doesn't need to keep the original
    /// request).
    #[prost(message, optional, tag = "2")]
    pub request: ::core::option::Option<EngineReloadRequest>,
}
/// Nested message and enum types in `EngineReloadResponse`.
pub mod engine_reload_response {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum Status {
        /// Reload command is accepted.
        Accepted = 0,
        /// New data is verified and ready.
        ReloadReady = 1,
        /// Engine was replaced by a new instance.
        Reloaded = 2,
        /// Failed to start reload because another reload job is currently running.
        AlreadyRunning = 3,
        /// Errors in data file.
        EngineVersionMismatch = 4,
        DataMissing = 5,
        DataBroken = 6,
        /// File doesn't exist or underlying memory mapping failed.
        MmapFailure = 7,
        UnknownError = 9,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Accepted => "ACCEPTED",
                Self::ReloadReady => "RELOAD_READY",
                Self::Reloaded => "RELOADED",
                Self::AlreadyRunning => "ALREADY_RUNNING",
                Self::EngineVersionMismatch => "ENGINE_VERSION_MISMATCH",
                Self::DataMissing => "DATA_MISSING",
                Self::DataBroken => "DATA_BROKEN",
                Self::MmapFailure => "MMAP_FAILURE",
                Self::UnknownError => "UNKNOWN_ERROR",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ACCEPTED" => Some(Self::Accepted),
                "RELOAD_READY" => Some(Self::ReloadReady),
                "RELOADED" => Some(Self::Reloaded),
                "ALREADY_RUNNING" => Some(Self::AlreadyRunning),
                "ENGINE_VERSION_MISMATCH" => Some(Self::EngineVersionMismatch),
                "DATA_MISSING" => Some(Self::DataMissing),
                "DATA_BROKEN" => Some(Self::DataBroken),
                "MMAP_FAILURE" => Some(Self::MmapFailure),
                "UNKNOWN_ERROR" => Some(Self::UnknownError),
                _ => None,
            }
        }
    }
}
