// This file is @generated by prost-build.
/// ////////////////////////////////////////////////////////////
///
/// General config (1-9)
///
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GeneralConfig {
    /// config version, corresponding to the suffix of config file
    #[prost(uint32, optional, tag = "1", default = "0")]
    pub config_version: ::core::option::Option<u32>,
    /// The product version that wrote this config
    #[prost(string, optional, tag = "2", default = "0.0.0.0")]
    pub last_modified_product_version: ::core::option::Option<
        ::prost::alloc::string::String,
    >,
    /// last modified time in UTC second
    #[prost(uint64, optional, tag = "3", default = "0")]
    pub last_modified_time: ::core::option::Option<u64>,
    /// These fields are not used now
    /// platform of machine that wrote this config
    #[prost(string, optional, tag = "4", default = "")]
    pub platform: ::core::option::Option<::prost::alloc::string::String>,
    /// UI locale of machine that wrote this config
    #[prost(string, optional, tag = "5", default = "")]
    pub ui_locale: ::core::option::Option<::prost::alloc::string::String>,
    /// Whether to upload usage stats
    /// This flag is used only for Android.
    #[prost(bool, optional, tag = "6", default = "false")]
    pub upload_usage_stats: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Config {
    /// General config and logging/debugging:
    /// We won't use 2-9 and 20-39 ids anymore for historical reasons.
    #[prost(message, optional, tag = "1")]
    pub general_config: ::core::option::Option<GeneralConfig>,
    /// set verbose level of logging library (FLAGS_v)
    #[prost(int32, optional, tag = "10", default = "0")]
    pub verbose_level: ::core::option::Option<i32>,
    /// Incognito mode:
    /// Disable all mutable operation if incognito_mode is true
    /// Clients needs to check ConversionRequest::incognito_mode() instead
    /// of Config::incognito_mode(), as the incoginto mode can also set
    /// via Options.
    #[prost(bool, optional, tag = "20", default = "false")]
    pub incognito_mode: ::core::option::Option<bool>,
    /// whether to show the set default dialog on startup
    #[prost(bool, optional, tag = "22", default = "true")]
    pub check_default: ::core::option::Option<bool>,
    /// Presentation mode:
    /// disable all suggestion temporally.
    #[prost(bool, optional, tag = "23", default = "false")]
    pub presentation_mode: ::core::option::Option<bool>,
    /// Roman/Kana
    #[prost(
        enumeration = "config::PreeditMethod",
        optional,
        tag = "40",
        default = "Roman"
    )]
    pub preedit_method: ::core::option::Option<i32>,
    #[prost(
        enumeration = "config::SessionKeymap",
        optional,
        tag = "41",
        default = "None"
    )]
    pub session_keymap: ::core::option::Option<i32>,
    /// custom keymap
    /// TODO(taku): replace it with repeated field
    #[prost(bytes = "vec", optional, tag = "42")]
    pub custom_keymap_table: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    /// custom roman table
    #[prost(bytes = "vec", optional, tag = "43")]
    pub custom_roman_table: ::core::option::Option<::prost::alloc::vec::Vec<u8>>,
    #[prost(
        enumeration = "config::PunctuationMethod",
        optional,
        tag = "45",
        default = "ToutenKuten"
    )]
    pub punctuation_method: ::core::option::Option<i32>,
    #[prost(
        enumeration = "config::SymbolMethod",
        optional,
        tag = "46",
        default = "CornerBracketMiddleDot"
    )]
    pub symbol_method: ::core::option::Option<i32>,
    #[prost(
        enumeration = "config::FundamentalCharacterForm",
        optional,
        tag = "47",
        default = "FundamentalInputMode"
    )]
    pub space_character_form: ::core::option::Option<i32>,
    /// If this flag is true, Mozc toggles preedit method with some predefined
    /// key events when IME is turned on.  Otherwise, Mozc ignores such kind of
    /// key events so that their preferred can be preserved even when the toggle
    /// key is pressed by accident.
    /// As for Mozc, only Windows client supports such kind of toggle so this flag
    /// is currently valid only on Windows.
    ///
    /// Background:
    ///    Traditional Japanese IMEs have used "Roma-Ji" key in Japanese 106/109
    ///    keyboard to toggle the preedit method between Roman and Kana style and
    ///    this behavior was finally adopted into JIS X 4064:2002 as a basic
    ///    functionality which is expected to support by a Japanese Input Method.
    ///    However, people who are not aware of this functionality have been
    ///    puzzled because the default key stroke is likely to be pressed
    ///    by accident.
    #[prost(bool, optional, tag = "48", default = "false")]
    pub use_keyboard_to_change_preedit_method: ::core::option::Option<bool>,
    #[prost(
        enumeration = "config::HistoryLearningLevel",
        optional,
        tag = "50",
        default = "DefaultHistory"
    )]
    pub history_learning_level: ::core::option::Option<i32>,
    #[prost(
        enumeration = "config::SelectionShortcut",
        optional,
        tag = "52",
        default = "Shortcut123456789"
    )]
    pub selection_shortcut: ::core::option::Option<i32>,
    #[prost(message, repeated, tag = "54")]
    pub character_form_rules: ::prost::alloc::vec::Vec<config::CharacterFormRule>,
    /// Automatically switch composition mode.
    #[prost(bool, optional, tag = "56", default = "true")]
    pub auto_switch_composition_mode: ::core::option::Option<bool>,
    /// Toggle to use cascanding window for debugging.
    #[prost(bool, optional, tag = "58", default = "true")]
    pub use_cascading_window: ::core::option::Option<bool>,
    #[prost(
        enumeration = "config::ShiftKeyModeSwitch",
        optional,
        tag = "59",
        default = "AsciiInputMode"
    )]
    pub shift_key_mode_switch: ::core::option::Option<i32>,
    #[prost(
        enumeration = "config::NumpadCharacterForm",
        optional,
        tag = "60",
        default = "NumpadHalfWidth"
    )]
    pub numpad_character_form: ::core::option::Option<i32>,
    #[prost(bool, optional, tag = "61", default = "false")]
    pub use_auto_conversion: ::core::option::Option<bool>,
    /// can't use AutoConversionKey as a type since
    /// undefined enum type is not correctly handled.
    #[prost(uint32, optional, tag = "62", default = "13")]
    pub auto_conversion_key: ::core::option::Option<u32>,
    /// Mac-original JIS key layout has "yen-sign" key which generates
    /// U+00A5 instead of U+005C and sometimes users get troubles with
    /// them because they expect backslashes which are rendered as
    /// yen-sign.  If this configuration is BACKSLASH, Mozc will
    /// interpret U+005C even when the original key event is U+00A5.
    #[prost(
        enumeration = "config::YenSignCharacter",
        optional,
        tag = "63",
        default = "YenSign"
    )]
    pub yen_sign_character: ::core::option::Option<i32>,
    /// Use Japanese keyboard layout even when the user uses other
    /// keyboard layouts.  In Mac OSX people can use several keyboard
    /// layouts such like French or Spanish but some people want to use
    /// Japanese layout for Japanese.  See <http://b/2917320>
    #[prost(bool, optional, tag = "64", default = "false")]
    pub use_japanese_layout: ::core::option::Option<bool>,
    /// Use kana modifier insensitive conversion.
    /// e.g. かつこう -> 学校
    /// Note that Request message has the same field.
    /// - Request's one is controlled by the client. A user cannot control it.
    ///    On the other hand Config's is under a user's control.
    /// - Whether the feature is activated or not is decided by logical-AND
    ///    of Request's and Config's.
    #[prost(bool, optional, tag = "65", default = "false")]
    pub use_kana_modifier_insensitive_conversion: ::core::option::Option<bool>,
    /// Use typing correction feature.
    /// e.g. sunkai -> 深海
    #[prost(bool, optional, tag = "66", default = "false")]
    pub use_typing_correction: ::core::option::Option<bool>,
    /// The duration in millisecond to determine the timeout.
    /// If the duration between key inputs is more than this value,
    /// a SessionCommand::STOP_KEY_TOGGLING is prepended to the next key input.
    /// If the value is 0, STOP_KEY_TOGGLING is not sent.
    #[prost(int32, optional, tag = "67", default = "0")]
    pub composing_timeout_threshold_msec: ::core::option::Option<i32>,
    /// The keymaps which are loaded on top of `session_keymap`.
    /// Overlay keymaps are prioritized over `session_keymap`.
    /// They are used to partially modify the session keymap, for example
    /// using Henkan key as IME_ON.
    #[prost(enumeration = "config::SessionKeymap", repeated, tag = "68")]
    pub overlay_keymaps: ::prost::alloc::vec::Vec<i32>,
    /// ////////////////////////////////////////////////////////////
    ///
    /// Dictionary (80-99)
    ///
    #[prost(bool, optional, tag = "80", default = "true")]
    pub use_date_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "81", default = "true")]
    pub use_single_kanji_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "82", default = "true")]
    pub use_symbol_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "83", default = "true")]
    pub use_number_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "84", default = "true")]
    pub use_emoticon_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "85", default = "true")]
    pub use_calculator: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "86", default = "true")]
    pub use_t13n_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "87", default = "true")]
    pub use_zip_code_conversion: ::core::option::Option<bool>,
    #[prost(bool, optional, tag = "88", default = "true")]
    pub use_spelling_correction: ::core::option::Option<bool>,
    /// If use_emoji_conversion is true, the user can input emoji characters
    /// by converting from a query string (e.g. "いぬ → 🐶" \[U+1F436\]).
    /// Even if it is false, users might be able to input emoji characters
    /// with other ways.
    /// Note: Some characters can be either of text and emoji.  It would be ideal
    /// to use the variation sequence to specify emoji presentation \[U+FE0E\],
    /// although it is not implemented yet.
    /// See: <http://unicode.org/reports/tr51/#Presentation_Style>
    #[prost(bool, optional, tag = "89", default = "false")]
    pub use_emoji_conversion: ::core::option::Option<bool>,
    #[prost(message, optional, tag = "90")]
    pub information_list_config: ::core::option::Option<config::InformationListConfig>,
    /// ////////////////////////////////////////////////////////////
    ///
    /// Suggest (100-119)
    ///
    /// Suggest is a feature of word suggestion with prefix search.
    /// When you type "あ", you may get "ありがとう", "朝" (あさ), "明日" (あした)
    /// as suggested words.
    ///
    /// Use history-based suggest feature.
    /// If this is true, your previously typed words are prioritized.
    #[prost(bool, optional, tag = "100", default = "true")]
    pub use_history_suggest: ::core::option::Option<bool>,
    /// Use dictionary-based suggest feature.
    /// If this is true, words in the word dictionary are suggested even if
    /// you haven't typed before.
    #[prost(bool, optional, tag = "101", default = "true")]
    pub use_dictionary_suggest: ::core::option::Option<bool>,
    /// Use realtime conversion feature.
    #[prost(bool, optional, tag = "102", default = "true")]
    pub use_realtime_conversion: ::core::option::Option<bool>,
    /// Size of suggestions.
    #[prost(uint32, optional, tag = "110", default = "3")]
    pub suggestions_size: ::core::option::Option<u32>,
    /// ////////////////////////////////////////////////////////////
    ///
    /// Renderer (120-139)
    ///
    /// Use mode indicator feature.
    #[prost(bool, optional, tag = "120", default = "true")]
    pub use_mode_indicator: ::core::option::Option<bool>,
}
/// Nested message and enum types in `Config`.
pub mod config {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct CharacterFormRule {
        #[prost(string, optional, tag = "1")]
        pub group: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(
            enumeration = "CharacterForm",
            optional,
            tag = "2",
            default = "FullWidth"
        )]
        pub preedit_character_form: ::core::option::Option<i32>,
        #[prost(
            enumeration = "CharacterForm",
            optional,
            tag = "3",
            default = "FullWidth"
        )]
        pub conversion_character_form: ::core::option::Option<i32>,
    }
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct InformationListConfig {
        #[prost(bool, optional, tag = "1", default = "true")]
        pub use_local_usage_dictionary: ::core::option::Option<bool>,
    }
    /// ////////////////////////////////////////////////////////////
    ///
    /// Basic features (40-79)
    ///
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PreeditMethod {
        Roman = 0,
        Kana = 1,
    }
    impl PreeditMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Roman => "ROMAN",
                Self::Kana => "KANA",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "ROMAN" => Some(Self::Roman),
                "KANA" => Some(Self::Kana),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SessionKeymap {
        /// If NONE is selected, it will be replaced with MSIME or KOTOERI.
        /// NONE is used only for a placeholder, so a configuration program
        /// should not show NONE as one of selections.  NONE should be the
        /// last of the items due to the limitation of the Qt GUI's
        /// implementation. Note that keymap number should be correspoinding
        /// to the index of QComboBox in config dialog. Since NONE is not
        /// used, we set -1 here.
        None = -1,
        Custom = 0,
        Atok = 1,
        Msime = 2,
        Kotoeri = 3,
        Mobile = 4,
        Chromeos = 5,
        OverlayHenkanMuhenkanToImeOnOff = 100,
        OverlayForTest = 10000,
    }
    impl SessionKeymap {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::None => "NONE",
                Self::Custom => "CUSTOM",
                Self::Atok => "ATOK",
                Self::Msime => "MSIME",
                Self::Kotoeri => "KOTOERI",
                Self::Mobile => "MOBILE",
                Self::Chromeos => "CHROMEOS",
                Self::OverlayHenkanMuhenkanToImeOnOff => {
                    "OVERLAY_HENKAN_MUHENKAN_TO_IME_ON_OFF"
                }
                Self::OverlayForTest => "OVERLAY_FOR_TEST",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NONE" => Some(Self::None),
                "CUSTOM" => Some(Self::Custom),
                "ATOK" => Some(Self::Atok),
                "MSIME" => Some(Self::Msime),
                "KOTOERI" => Some(Self::Kotoeri),
                "MOBILE" => Some(Self::Mobile),
                "CHROMEOS" => Some(Self::Chromeos),
                "OVERLAY_HENKAN_MUHENKAN_TO_IME_ON_OFF" => {
                    Some(Self::OverlayHenkanMuhenkanToImeOnOff)
                }
                "OVERLAY_FOR_TEST" => Some(Self::OverlayForTest),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PunctuationMethod {
        ToutenKuten = 0,
        CommaPeriod = 1,
        ToutenPeriod = 2,
        CommaKuten = 3,
    }
    impl PunctuationMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::ToutenKuten => "TOUTEN_KUTEN",
                Self::CommaPeriod => "COMMA_PERIOD",
                Self::ToutenPeriod => "TOUTEN_PERIOD",
                Self::CommaKuten => "COMMA_KUTEN",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "TOUTEN_KUTEN" => Some(Self::ToutenKuten),
                "COMMA_PERIOD" => Some(Self::CommaPeriod),
                "TOUTEN_PERIOD" => Some(Self::ToutenPeriod),
                "COMMA_KUTEN" => Some(Self::CommaKuten),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SymbolMethod {
        CornerBracketMiddleDot = 0,
        SquareBracketSlash = 1,
        CornerBracketSlash = 2,
        SquareBracketMiddleDot = 3,
    }
    impl SymbolMethod {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::CornerBracketMiddleDot => "CORNER_BRACKET_MIDDLE_DOT",
                Self::SquareBracketSlash => "SQUARE_BRACKET_SLASH",
                Self::CornerBracketSlash => "CORNER_BRACKET_SLASH",
                Self::SquareBracketMiddleDot => "SQUARE_BRACKET_MIDDLE_DOT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "CORNER_BRACKET_MIDDLE_DOT" => Some(Self::CornerBracketMiddleDot),
                "SQUARE_BRACKET_SLASH" => Some(Self::SquareBracketSlash),
                "CORNER_BRACKET_SLASH" => Some(Self::CornerBracketSlash),
                "SQUARE_BRACKET_MIDDLE_DOT" => Some(Self::SquareBracketMiddleDot),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum FundamentalCharacterForm {
        /// follow the input mode
        FundamentalInputMode = 0,
        /// always FullWidth
        FundamentalFullWidth = 1,
        /// always HalfWidth
        FundamentalHalfWidth = 2,
    }
    impl FundamentalCharacterForm {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::FundamentalInputMode => "FUNDAMENTAL_INPUT_MODE",
                Self::FundamentalFullWidth => "FUNDAMENTAL_FULL_WIDTH",
                Self::FundamentalHalfWidth => "FUNDAMENTAL_HALF_WIDTH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "FUNDAMENTAL_INPUT_MODE" => Some(Self::FundamentalInputMode),
                "FUNDAMENTAL_FULL_WIDTH" => Some(Self::FundamentalFullWidth),
                "FUNDAMENTAL_HALF_WIDTH" => Some(Self::FundamentalHalfWidth),
                _ => None,
            }
        }
    }
    /// User history learning
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum HistoryLearningLevel {
        DefaultHistory = 0,
        ReadOnly = 1,
        NoHistory = 2,
    }
    impl HistoryLearningLevel {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::DefaultHistory => "DEFAULT_HISTORY",
                Self::ReadOnly => "READ_ONLY",
                Self::NoHistory => "NO_HISTORY",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DEFAULT_HISTORY" => Some(Self::DefaultHistory),
                "READ_ONLY" => Some(Self::ReadOnly),
                "NO_HISTORY" => Some(Self::NoHistory),
                _ => None,
            }
        }
    }
    /// The style of candidate selection shortcut.
    /// Note that if the current Request has SpecialRomajiTable (== the keyevent
    /// is from a virtual keyboard), shortcut is no-op.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum SelectionShortcut {
        NoShortcut = 0,
        Shortcut123456789 = 1,
        ShortcutAsdfghjkl = 2,
    }
    impl SelectionShortcut {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NoShortcut => "NO_SHORTCUT",
                Self::Shortcut123456789 => "SHORTCUT_123456789",
                Self::ShortcutAsdfghjkl => "SHORTCUT_ASDFGHJKL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NO_SHORTCUT" => Some(Self::NoShortcut),
                "SHORTCUT_123456789" => Some(Self::Shortcut123456789),
                "SHORTCUT_ASDFGHJKL" => Some(Self::ShortcutAsdfghjkl),
                _ => None,
            }
        }
    }
    /// character form (Halfwidth/Fullwidth
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum CharacterForm {
        HalfWidth = 0,
        FullWidth = 1,
        LastForm = 2,
        NoConversion = 3,
    }
    impl CharacterForm {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::HalfWidth => "HALF_WIDTH",
                Self::FullWidth => "FULL_WIDTH",
                Self::LastForm => "LAST_FORM",
                Self::NoConversion => "NO_CONVERSION",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "HALF_WIDTH" => Some(Self::HalfWidth),
                "FULL_WIDTH" => Some(Self::FullWidth),
                "LAST_FORM" => Some(Self::LastForm),
                "NO_CONVERSION" => Some(Self::NoConversion),
                _ => None,
            }
        }
    }
    /// Shift key mode switch
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum ShiftKeyModeSwitch {
        /// Case insensitive
        Off = 0,
        /// MSIME, ATOK behavior
        AsciiInputMode = 1,
        /// Kotoeri behavior
        KatakanaInputMode = 2,
    }
    impl ShiftKeyModeSwitch {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Off => "OFF",
                Self::AsciiInputMode => "ASCII_INPUT_MODE",
                Self::KatakanaInputMode => "KATAKANA_INPUT_MODE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "OFF" => Some(Self::Off),
                "ASCII_INPUT_MODE" => Some(Self::AsciiInputMode),
                "KATAKANA_INPUT_MODE" => Some(Self::KatakanaInputMode),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum NumpadCharacterForm {
        NumpadInputMode = 0,
        NumpadFullWidth = 1,
        NumpadHalfWidth = 2,
        NumpadDirectInput = 3,
    }
    impl NumpadCharacterForm {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NumpadInputMode => "NUMPAD_INPUT_MODE",
                Self::NumpadFullWidth => "NUMPAD_FULL_WIDTH",
                Self::NumpadHalfWidth => "NUMPAD_HALF_WIDTH",
                Self::NumpadDirectInput => "NUMPAD_DIRECT_INPUT",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NUMPAD_INPUT_MODE" => Some(Self::NumpadInputMode),
                "NUMPAD_FULL_WIDTH" => Some(Self::NumpadFullWidth),
                "NUMPAD_HALF_WIDTH" => Some(Self::NumpadHalfWidth),
                "NUMPAD_DIRECT_INPUT" => Some(Self::NumpadDirectInput),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AutoConversionKey {
        AutoConversionOff = 0,
        AutoConversionKuten = 1,
        AutoConversionTouten = 2,
        AutoConversionQuestionMark = 4,
        AutoConversionExclamationMark = 8,
    }
    impl AutoConversionKey {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::AutoConversionOff => "AUTO_CONVERSION_OFF",
                Self::AutoConversionKuten => "AUTO_CONVERSION_KUTEN",
                Self::AutoConversionTouten => "AUTO_CONVERSION_TOUTEN",
                Self::AutoConversionQuestionMark => "AUTO_CONVERSION_QUESTION_MARK",
                Self::AutoConversionExclamationMark => "AUTO_CONVERSION_EXCLAMATION_MARK",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "AUTO_CONVERSION_OFF" => Some(Self::AutoConversionOff),
                "AUTO_CONVERSION_KUTEN" => Some(Self::AutoConversionKuten),
                "AUTO_CONVERSION_TOUTEN" => Some(Self::AutoConversionTouten),
                "AUTO_CONVERSION_QUESTION_MARK" => Some(Self::AutoConversionQuestionMark),
                "AUTO_CONVERSION_EXCLAMATION_MARK" => {
                    Some(Self::AutoConversionExclamationMark)
                }
                _ => None,
            }
        }
    }
    /// Mac only config items: yen_sign_character and use_japanese_layout.
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum YenSignCharacter {
        YenSign = 0,
        Backslash = 1,
    }
    impl YenSignCharacter {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::YenSign => "YEN_SIGN",
                Self::Backslash => "BACKSLASH",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "YEN_SIGN" => Some(Self::YenSign),
                "BACKSLASH" => Some(Self::Backslash),
                _ => None,
            }
        }
    }
}
