// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserDictionary {
    /// LINT.ThenChange(
    ///      dictionary/user_dictionary_util.cc
    /// )
    /// ID of this dictionary
    #[prost(uint64, optional, tag = "1", default = "0")]
    pub id: ::core::option::Option<u64>,
    /// name of dictionary
    #[prost(string, optional, tag = "3", default = "")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "4")]
    pub entries: ::prost::alloc::vec::Vec<user_dictionary::Entry>,
}
/// Nested message and enum types in `UserDictionary`.
pub mod user_dictionary {
    /// entry of each word
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Entry {
        #[prost(string, optional, tag = "1", default = "")]
        pub key: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "2", default = "")]
        pub value: ::core::option::Option<::prost::alloc::string::String>,
        #[prost(string, optional, tag = "4", default = "")]
        pub comment: ::core::option::Option<::prost::alloc::string::String>,
        /// Historically we used to use tag number '3' for POS in string format.
        /// In order to switch it to enum based POS, we removed (deprecated) the
        /// tag number '3' field and created another field numbered '5'.
        /// Historically the default POS tag was NOUN, and "NO_POS" is added later.
        /// In order to preserve the original default behavior, default POS tag is
        /// explicitly specified as NOUN. However, this can be changed if there is no
        /// problem with "NO_POS".
        #[prost(enumeration = "PosType", optional, tag = "5", default = "Noun")]
        pub pos: ::core::option::Option<i32>,
        /// In multilingual settings, Gboard's personal dictionary will feed entries
        /// with locale information. We can change the behavior (filter or demote)
        /// The locale is usually formatted in BCP47.
        /// In TSV format, the locale is encoded in the POS field as `pos:locale`
        /// "名詞:ja".
        #[prost(string, optional, tag = "12", default = "")]
        pub locale: ::core::option::Option<::prost::alloc::string::String>,
    }
    /// LINT.IfChange
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum PosType {
        /// Use this when the POS tag is not provided or unknown.
        ///
        /// "品詞なし"
        NoPos = 0,
        /// "名詞"
        Noun = 1,
        /// "短縮よみ"
        Abbreviation = 2,
        /// "サジェストのみ"
        SuggestionOnly = 3,
        /// "固有名詞"
        ProperNoun = 4,
        /// "人名"
        PersonalName = 5,
        /// "姓"
        FamilyName = 6,
        /// "名"
        FirstName = 7,
        /// "組織"
        OrganizationName = 8,
        /// "地名"
        PlaceName = 9,
        /// "名詞サ変"
        SaIrregularConjugationNoun = 10,
        /// "名詞形動"
        AdjectiveVerbalNoun = 11,
        /// "数"
        Number = 12,
        /// "アルファベット"
        Alphabet = 13,
        /// "記号"
        Symbol = 14,
        /// "顔文字"
        Emoticon = 15,
        /// "副詞"
        Adverb = 16,
        /// "連体詞"
        PrenounAdjectival = 17,
        /// "接続詞"
        Conjunction = 18,
        /// "感動詞"
        Interjection = 19,
        /// "接頭語"
        Prefix = 20,
        /// "助数詞"
        CounterSuffix = 21,
        /// "接尾一般"
        GenericSuffix = 22,
        /// "接尾人名"
        PersonNameSuffix = 23,
        /// "接尾地名"
        PlaceNameSuffix = 24,
        /// "動詞ワ行五段"
        WaGroup1Verb = 25,
        /// "動詞カ行五段"
        KaGroup1Verb = 26,
        /// "動詞サ行五段"
        SaGroup1Verb = 27,
        /// "動詞タ行五段"
        TaGroup1Verb = 28,
        /// "動詞ナ行五段"
        NaGroup1Verb = 29,
        /// "動詞マ行五段"
        MaGroup1Verb = 30,
        /// "動詞ラ行五段"
        RaGroup1Verb = 31,
        /// "動詞ガ行五段"
        GaGroup1Verb = 32,
        /// "動詞バ行五段"
        BaGroup1Verb = 33,
        /// "動詞ハ行四段"
        HaGroup1Verb = 34,
        /// "動詞一段"
        Group2Verb = 35,
        /// "動詞カ変"
        KuruGroup3Verb = 36,
        /// "動詞サ変"
        SuruGroup3Verb = 37,
        /// "動詞ザ変"
        ZuruGroup3Verb = 38,
        /// "動詞ラ変"
        RuGroup3Verb = 39,
        /// "形容詞"
        Adjective = 40,
        /// "終助詞"
        SentenceEndingParticle = 41,
        /// "句読点"
        Punctuation = 42,
        /// "独立語"
        FreeStandingWord = 43,
        /// "抑制単語"
        SuppressionWord = 44,
    }
    impl PosType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::NoPos => "NO_POS",
                Self::Noun => "NOUN",
                Self::Abbreviation => "ABBREVIATION",
                Self::SuggestionOnly => "SUGGESTION_ONLY",
                Self::ProperNoun => "PROPER_NOUN",
                Self::PersonalName => "PERSONAL_NAME",
                Self::FamilyName => "FAMILY_NAME",
                Self::FirstName => "FIRST_NAME",
                Self::OrganizationName => "ORGANIZATION_NAME",
                Self::PlaceName => "PLACE_NAME",
                Self::SaIrregularConjugationNoun => "SA_IRREGULAR_CONJUGATION_NOUN",
                Self::AdjectiveVerbalNoun => "ADJECTIVE_VERBAL_NOUN",
                Self::Number => "NUMBER",
                Self::Alphabet => "ALPHABET",
                Self::Symbol => "SYMBOL",
                Self::Emoticon => "EMOTICON",
                Self::Adverb => "ADVERB",
                Self::PrenounAdjectival => "PRENOUN_ADJECTIVAL",
                Self::Conjunction => "CONJUNCTION",
                Self::Interjection => "INTERJECTION",
                Self::Prefix => "PREFIX",
                Self::CounterSuffix => "COUNTER_SUFFIX",
                Self::GenericSuffix => "GENERIC_SUFFIX",
                Self::PersonNameSuffix => "PERSON_NAME_SUFFIX",
                Self::PlaceNameSuffix => "PLACE_NAME_SUFFIX",
                Self::WaGroup1Verb => "WA_GROUP1_VERB",
                Self::KaGroup1Verb => "KA_GROUP1_VERB",
                Self::SaGroup1Verb => "SA_GROUP1_VERB",
                Self::TaGroup1Verb => "TA_GROUP1_VERB",
                Self::NaGroup1Verb => "NA_GROUP1_VERB",
                Self::MaGroup1Verb => "MA_GROUP1_VERB",
                Self::RaGroup1Verb => "RA_GROUP1_VERB",
                Self::GaGroup1Verb => "GA_GROUP1_VERB",
                Self::BaGroup1Verb => "BA_GROUP1_VERB",
                Self::HaGroup1Verb => "HA_GROUP1_VERB",
                Self::Group2Verb => "GROUP2_VERB",
                Self::KuruGroup3Verb => "KURU_GROUP3_VERB",
                Self::SuruGroup3Verb => "SURU_GROUP3_VERB",
                Self::ZuruGroup3Verb => "ZURU_GROUP3_VERB",
                Self::RuGroup3Verb => "RU_GROUP3_VERB",
                Self::Adjective => "ADJECTIVE",
                Self::SentenceEndingParticle => "SENTENCE_ENDING_PARTICLE",
                Self::Punctuation => "PUNCTUATION",
                Self::FreeStandingWord => "FREE_STANDING_WORD",
                Self::SuppressionWord => "SUPPRESSION_WORD",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "NO_POS" => Some(Self::NoPos),
                "NOUN" => Some(Self::Noun),
                "ABBREVIATION" => Some(Self::Abbreviation),
                "SUGGESTION_ONLY" => Some(Self::SuggestionOnly),
                "PROPER_NOUN" => Some(Self::ProperNoun),
                "PERSONAL_NAME" => Some(Self::PersonalName),
                "FAMILY_NAME" => Some(Self::FamilyName),
                "FIRST_NAME" => Some(Self::FirstName),
                "ORGANIZATION_NAME" => Some(Self::OrganizationName),
                "PLACE_NAME" => Some(Self::PlaceName),
                "SA_IRREGULAR_CONJUGATION_NOUN" => Some(Self::SaIrregularConjugationNoun),
                "ADJECTIVE_VERBAL_NOUN" => Some(Self::AdjectiveVerbalNoun),
                "NUMBER" => Some(Self::Number),
                "ALPHABET" => Some(Self::Alphabet),
                "SYMBOL" => Some(Self::Symbol),
                "EMOTICON" => Some(Self::Emoticon),
                "ADVERB" => Some(Self::Adverb),
                "PRENOUN_ADJECTIVAL" => Some(Self::PrenounAdjectival),
                "CONJUNCTION" => Some(Self::Conjunction),
                "INTERJECTION" => Some(Self::Interjection),
                "PREFIX" => Some(Self::Prefix),
                "COUNTER_SUFFIX" => Some(Self::CounterSuffix),
                "GENERIC_SUFFIX" => Some(Self::GenericSuffix),
                "PERSON_NAME_SUFFIX" => Some(Self::PersonNameSuffix),
                "PLACE_NAME_SUFFIX" => Some(Self::PlaceNameSuffix),
                "WA_GROUP1_VERB" => Some(Self::WaGroup1Verb),
                "KA_GROUP1_VERB" => Some(Self::KaGroup1Verb),
                "SA_GROUP1_VERB" => Some(Self::SaGroup1Verb),
                "TA_GROUP1_VERB" => Some(Self::TaGroup1Verb),
                "NA_GROUP1_VERB" => Some(Self::NaGroup1Verb),
                "MA_GROUP1_VERB" => Some(Self::MaGroup1Verb),
                "RA_GROUP1_VERB" => Some(Self::RaGroup1Verb),
                "GA_GROUP1_VERB" => Some(Self::GaGroup1Verb),
                "BA_GROUP1_VERB" => Some(Self::BaGroup1Verb),
                "HA_GROUP1_VERB" => Some(Self::HaGroup1Verb),
                "GROUP2_VERB" => Some(Self::Group2Verb),
                "KURU_GROUP3_VERB" => Some(Self::KuruGroup3Verb),
                "SURU_GROUP3_VERB" => Some(Self::SuruGroup3Verb),
                "ZURU_GROUP3_VERB" => Some(Self::ZuruGroup3Verb),
                "RU_GROUP3_VERB" => Some(Self::RuGroup3Verb),
                "ADJECTIVE" => Some(Self::Adjective),
                "SENTENCE_ENDING_PARTICLE" => Some(Self::SentenceEndingParticle),
                "PUNCTUATION" => Some(Self::Punctuation),
                "FREE_STANDING_WORD" => Some(Self::FreeStandingWord),
                "SUPPRESSION_WORD" => Some(Self::SuppressionWord),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UserDictionaryStorage {
    /// version of user dictionary
    #[prost(int32, optional, tag = "1", default = "0")]
    pub version: ::core::option::Option<i32>,
    /// dictionary body
    #[prost(message, repeated, tag = "2")]
    pub dictionaries: ::prost::alloc::vec::Vec<UserDictionary>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UserDictionaryImportData {
    #[prost(string, optional, tag = "1")]
    pub dictionary_name: ::core::option::Option<::prost::alloc::string::String>,
    /// TSV data.
    #[prost(string, optional, tag = "2")]
    pub data: ::core::option::Option<::prost::alloc::string::String>,
}
