[package]
name = "ime-tsf"
version = "0.1.0"
edition = "2021"
description = "地球桌面输入法的 TSF 文本服务（加载进每个打字的程序）"

[lib]
name = "EarthDeskTSF"
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ime-proto = { path = "../proto" }

[target.'cfg(windows)'.dependencies.windows]
workspace = true
features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_Storage_FileSystem",
  "Win32_System_Com",
  "Win32_System_Ole",
  "Win32_System_Variant",
  "Win32_System_IO",
  "Win32_System_Pipes",
  "Win32_System_Threading",
  "Win32_System_LibraryLoader",
  "Win32_System_Registry",
  "Win32_System_RemoteDesktop",
  "Win32_System_SystemServices",
  "Win32_UI_HiDpi",
  "Win32_Graphics_Gdi",
  "Win32_UI_Shell",
  "Win32_UI_TextServices",
  "Win32_UI_Input_KeyboardAndMouse",
  "Win32_UI_WindowsAndMessaging",
]

[target.'cfg(windows)'.dependencies.windows-core]
workspace = true
