//! librime's C API, generated by bindgen from rime_api.h (librime 1.17.0).
//! Newer fields only ever get appended to `RimeApi`, so an older library
//! (Linux test machines ship 1.10) is fine as long as `data_size` is checked
//! before calling anything recent (see `rime.rs::has`).
#![allow(non_camel_case_types, non_snake_case, dead_code, clippy::all)]


pub type RimeSessionId = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_traits_t {
    pub data_size: ::core::ffi::c_int,
    pub shared_data_dir: *const ::core::ffi::c_char,
    pub user_data_dir: *const ::core::ffi::c_char,
    pub distribution_name: *const ::core::ffi::c_char,
    pub distribution_code_name: *const ::core::ffi::c_char,
    pub distribution_version: *const ::core::ffi::c_char,
    pub app_name: *const ::core::ffi::c_char,
    pub modules: *mut *const ::core::ffi::c_char,
    pub min_log_level: ::core::ffi::c_int,
    pub log_dir: *const ::core::ffi::c_char,
    pub prebuilt_data_dir: *const ::core::ffi::c_char,
    pub staging_dir: *const ::core::ffi::c_char,
}
pub type RimeTraits = rime_traits_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RimeComposition {
    pub length: ::core::ffi::c_int,
    pub cursor_pos: ::core::ffi::c_int,
    pub sel_start: ::core::ffi::c_int,
    pub sel_end: ::core::ffi::c_int,
    pub preedit: *mut ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_candidate_t {
    pub text: *mut ::core::ffi::c_char,
    pub comment: *mut ::core::ffi::c_char,
    pub reserved: *mut ::core::ffi::c_void,
}
pub type RimeCandidate = rime_candidate_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RimeMenu {
    pub page_size: ::core::ffi::c_int,
    pub page_no: ::core::ffi::c_int,
    pub is_last_page: ::core::ffi::c_int,
    pub highlighted_candidate_index: ::core::ffi::c_int,
    pub num_candidates: ::core::ffi::c_int,
    pub candidates: *mut RimeCandidate,
    pub select_keys: *mut ::core::ffi::c_char,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_commit_t {
    pub data_size: ::core::ffi::c_int,
    pub text: *mut ::core::ffi::c_char,
}
pub type RimeCommit = rime_commit_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_context_t {
    pub data_size: ::core::ffi::c_int,
    pub composition: RimeComposition,
    pub menu: RimeMenu,
    pub commit_text_preview: *mut ::core::ffi::c_char,
    pub select_labels: *mut *mut ::core::ffi::c_char,
}
pub type RimeContext = rime_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_status_t {
    pub data_size: ::core::ffi::c_int,
    pub schema_id: *mut ::core::ffi::c_char,
    pub schema_name: *mut ::core::ffi::c_char,
    pub is_disabled: ::core::ffi::c_int,
    pub is_composing: ::core::ffi::c_int,
    pub is_ascii_mode: ::core::ffi::c_int,
    pub is_full_shape: ::core::ffi::c_int,
    pub is_simplified: ::core::ffi::c_int,
    pub is_traditional: ::core::ffi::c_int,
    pub is_ascii_punct: ::core::ffi::c_int,
}
pub type RimeStatus = rime_status_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_candidate_list_iterator_t {
    pub ptr: *mut ::core::ffi::c_void,
    pub index: ::core::ffi::c_int,
    pub candidate: RimeCandidate,
}
pub type RimeCandidateListIterator = rime_candidate_list_iterator_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_config_t {
    pub ptr: *mut ::core::ffi::c_void,
}
pub type RimeConfig = rime_config_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_config_iterator_t {
    pub list: *mut ::core::ffi::c_void,
    pub map: *mut ::core::ffi::c_void,
    pub index: ::core::ffi::c_int,
    pub key: *const ::core::ffi::c_char,
    pub path: *const ::core::ffi::c_char,
}
pub type RimeConfigIterator = rime_config_iterator_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_schema_list_item_t {
    pub schema_id: *mut ::core::ffi::c_char,
    pub name: *mut ::core::ffi::c_char,
    pub reserved: *mut ::core::ffi::c_void,
}
pub type RimeSchemaListItem = rime_schema_list_item_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_schema_list_t {
    pub size: usize,
    pub list: *mut RimeSchemaListItem,
}
pub type RimeSchemaList = rime_schema_list_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_string_slice_t {
    pub str_: *const ::core::ffi::c_char,
    pub length: usize,
}
pub type RimeStringSlice = rime_string_slice_t;
pub type RimeNotificationHandler = ::core::option::Option<
    unsafe extern "C" fn(
        context_object: *mut ::core::ffi::c_void,
        session_id: RimeSessionId,
        message_type: *const ::core::ffi::c_char,
        message_value: *const ::core::ffi::c_char,
    ),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_custom_api_t {
    pub data_size: ::core::ffi::c_int,
}
pub type RimeCustomApi = rime_custom_api_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_module_t {
    pub data_size: ::core::ffi::c_int,
    pub module_name: *const ::core::ffi::c_char,
    pub initialize: ::core::option::Option<unsafe extern "C" fn()>,
    pub finalize: ::core::option::Option<unsafe extern "C" fn()>,
    pub get_api: ::core::option::Option<unsafe extern "C" fn() -> *mut RimeCustomApi>,
}
pub type RimeModule = rime_module_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_api_t {
    pub data_size: ::core::ffi::c_int,
    pub setup: ::core::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub set_notification_handler: ::core::option::Option<
        unsafe extern "C" fn(
            handler: RimeNotificationHandler,
            context_object: *mut ::core::ffi::c_void,
        ),
    >,
    pub initialize: ::core::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub finalize: ::core::option::Option<unsafe extern "C" fn()>,
    pub start_maintenance: ::core::option::Option<
        unsafe extern "C" fn(full_check: ::core::ffi::c_int) -> ::core::ffi::c_int,
    >,
    pub is_maintenance_mode: ::core::option::Option<unsafe extern "C" fn() -> ::core::ffi::c_int>,
    pub join_maintenance_thread: ::core::option::Option<unsafe extern "C" fn()>,
    pub deployer_initialize: ::core::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub prebuild: ::core::option::Option<unsafe extern "C" fn() -> ::core::ffi::c_int>,
    pub deploy: ::core::option::Option<unsafe extern "C" fn() -> ::core::ffi::c_int>,
    pub deploy_schema: ::core::option::Option<
        unsafe extern "C" fn(schema_file: *const ::core::ffi::c_char) -> ::core::ffi::c_int,
    >,
    pub deploy_config_file: ::core::option::Option<
        unsafe extern "C" fn(
            file_name: *const ::core::ffi::c_char,
            version_key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub sync_user_data: ::core::option::Option<unsafe extern "C" fn() -> ::core::ffi::c_int>,
    pub create_session: ::core::option::Option<unsafe extern "C" fn() -> RimeSessionId>,
    pub find_session: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::core::ffi::c_int,
    >,
    pub destroy_session: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::core::ffi::c_int,
    >,
    pub cleanup_stale_sessions: ::core::option::Option<unsafe extern "C" fn()>,
    pub cleanup_all_sessions: ::core::option::Option<unsafe extern "C" fn()>,
    pub process_key: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            keycode: ::core::ffi::c_int,
            mask: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub commit_composition: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::core::ffi::c_int,
    >,
    pub clear_composition: ::core::option::Option<unsafe extern "C" fn(session_id: RimeSessionId)>,
    pub get_commit: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            commit: *mut RimeCommit,
        ) -> ::core::ffi::c_int,
    >,
    pub free_commit:
        ::core::option::Option<unsafe extern "C" fn(commit: *mut RimeCommit) -> ::core::ffi::c_int>,
    pub get_context: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            context: *mut RimeContext,
        ) -> ::core::ffi::c_int,
    >,
    pub free_context:
        ::core::option::Option<unsafe extern "C" fn(ctx: *mut RimeContext) -> ::core::ffi::c_int>,
    pub get_status: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            status: *mut RimeStatus,
        ) -> ::core::ffi::c_int,
    >,
    pub free_status:
        ::core::option::Option<unsafe extern "C" fn(status: *mut RimeStatus) -> ::core::ffi::c_int>,
    pub set_option: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option: *const ::core::ffi::c_char,
            value: ::core::ffi::c_int,
        ),
    >,
    pub get_option: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub set_property: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            prop: *const ::core::ffi::c_char,
            value: *const ::core::ffi::c_char,
        ),
    >,
    pub get_property: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            prop: *const ::core::ffi::c_char,
            value: *mut ::core::ffi::c_char,
            buffer_size: usize,
        ) -> ::core::ffi::c_int,
    >,
    pub get_schema_list: ::core::option::Option<
        unsafe extern "C" fn(schema_list: *mut RimeSchemaList) -> ::core::ffi::c_int,
    >,
    pub free_schema_list:
        ::core::option::Option<unsafe extern "C" fn(schema_list: *mut RimeSchemaList)>,
    pub get_current_schema: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            schema_id: *mut ::core::ffi::c_char,
            buffer_size: usize,
        ) -> ::core::ffi::c_int,
    >,
    pub select_schema: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            schema_id: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub schema_open: ::core::option::Option<
        unsafe extern "C" fn(
            schema_id: *const ::core::ffi::c_char,
            config: *mut RimeConfig,
        ) -> ::core::ffi::c_int,
    >,
    pub config_open: ::core::option::Option<
        unsafe extern "C" fn(
            config_id: *const ::core::ffi::c_char,
            config: *mut RimeConfig,
        ) -> ::core::ffi::c_int,
    >,
    pub config_close:
        ::core::option::Option<unsafe extern "C" fn(config: *mut RimeConfig) -> ::core::ffi::c_int>,
    pub config_get_bool: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub config_get_int: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub config_get_double: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut f64,
        ) -> ::core::ffi::c_int,
    >,
    pub config_get_string: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut ::core::ffi::c_char,
            buffer_size: usize,
        ) -> ::core::ffi::c_int,
    >,
    pub config_get_cstring: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> *const ::core::ffi::c_char,
    >,
    pub config_update_signature: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            signer: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_begin_map: ::core::option::Option<
        unsafe extern "C" fn(
            iterator: *mut RimeConfigIterator,
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_next: ::core::option::Option<
        unsafe extern "C" fn(iterator: *mut RimeConfigIterator) -> ::core::ffi::c_int,
    >,
    pub config_end: ::core::option::Option<unsafe extern "C" fn(iterator: *mut RimeConfigIterator)>,
    pub simulate_key_sequence: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            key_sequence: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub register_module:
        ::core::option::Option<unsafe extern "C" fn(module: *mut RimeModule) -> ::core::ffi::c_int>,
    pub find_module: ::core::option::Option<
        unsafe extern "C" fn(module_name: *const ::core::ffi::c_char) -> *mut RimeModule,
    >,
    pub run_task: ::core::option::Option<
        unsafe extern "C" fn(task_name: *const ::core::ffi::c_char) -> ::core::ffi::c_int,
    >,
    pub get_shared_data_dir:
        ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub get_user_data_dir:
        ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub get_sync_dir: ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub get_user_id: ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub get_user_data_sync_dir: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub config_init:
        ::core::option::Option<unsafe extern "C" fn(config: *mut RimeConfig) -> ::core::ffi::c_int>,
    pub config_load_string: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            yaml: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_set_bool: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub config_set_int: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub config_set_double: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: f64,
        ) -> ::core::ffi::c_int,
    >,
    pub config_set_string: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_get_item: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut RimeConfig,
        ) -> ::core::ffi::c_int,
    >,
    pub config_set_item: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
            value: *mut RimeConfig,
        ) -> ::core::ffi::c_int,
    >,
    pub config_clear: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_create_list: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_create_map: ::core::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub config_list_size: ::core::option::Option<
        unsafe extern "C" fn(config: *mut RimeConfig, key: *const ::core::ffi::c_char) -> usize,
    >,
    pub config_begin_list: ::core::option::Option<
        unsafe extern "C" fn(
            iterator: *mut RimeConfigIterator,
            config: *mut RimeConfig,
            key: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub get_input: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> *const ::core::ffi::c_char,
    >,
    pub get_caret_pos:
        ::core::option::Option<unsafe extern "C" fn(session_id: RimeSessionId) -> usize>,
    pub select_candidate: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub get_version: ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub set_caret_pos:
        ::core::option::Option<unsafe extern "C" fn(session_id: RimeSessionId, caret_pos: usize)>,
    pub select_candidate_on_current_page: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub candidate_list_begin: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            iterator: *mut RimeCandidateListIterator,
        ) -> ::core::ffi::c_int,
    >,
    pub candidate_list_next: ::core::option::Option<
        unsafe extern "C" fn(iterator: *mut RimeCandidateListIterator) -> ::core::ffi::c_int,
    >,
    pub candidate_list_end:
        ::core::option::Option<unsafe extern "C" fn(iterator: *mut RimeCandidateListIterator)>,
    pub user_config_open: ::core::option::Option<
        unsafe extern "C" fn(
            config_id: *const ::core::ffi::c_char,
            config: *mut RimeConfig,
        ) -> ::core::ffi::c_int,
    >,
    pub candidate_list_from_index: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            iterator: *mut RimeCandidateListIterator,
            index: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
    pub get_prebuilt_data_dir:
        ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub get_staging_dir:
        ::core::option::Option<unsafe extern "C" fn() -> *const ::core::ffi::c_char>,
    pub commit_proto: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, commit_builder: *mut ::core::ffi::c_void),
    >,
    pub context_proto: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, context_builder: *mut ::core::ffi::c_void),
    >,
    pub status_proto: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, status_builder: *mut ::core::ffi::c_void),
    >,
    pub get_state_label: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option_name: *const ::core::ffi::c_char,
            state: ::core::ffi::c_int,
        ) -> *const ::core::ffi::c_char,
    >,
    pub delete_candidate: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub delete_candidate_on_current_page: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub get_state_label_abbreviated: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option_name: *const ::core::ffi::c_char,
            state: ::core::ffi::c_int,
            abbreviated: ::core::ffi::c_int,
        ) -> RimeStringSlice,
    >,
    pub set_input: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            input: *const ::core::ffi::c_char,
        ) -> ::core::ffi::c_int,
    >,
    pub get_shared_data_dir_s: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub get_user_data_dir_s: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub get_prebuilt_data_dir_s: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub get_staging_dir_s: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub get_sync_dir_s: ::core::option::Option<
        unsafe extern "C" fn(dir: *mut ::core::ffi::c_char, buffer_size: usize),
    >,
    pub highlight_candidate: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub highlight_candidate_on_current_page: ::core::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::core::ffi::c_int,
    >,
    pub change_page: ::core::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            backward: ::core::ffi::c_int,
        ) -> ::core::ffi::c_int,
    >,
}
pub type RimeApi = rime_api_t;
